import { useEffect, useMemo, useRef, useState } from "react";
import "./tickets.css";

const categories = ["billing and payments", "account access", "technical issue", "product question"];
const examples = [
  ["Duplicate charge", "I was charged twice for my subscription this month. Please refund the duplicate payment."],
  ["Locked account", "I cannot sign in after resetting my password and I need access before my meeting today."],
  ["App keeps crashing", "The app closes every time I upload a PDF. I have restarted twice and it still happens."],
];
const actions: Record<string, string> = {
  "billing and payments": "Check the payment history and confirm refund eligibility.",
  "account access": "Verify the customer’s identity and begin account recovery.",
  "technical issue": "Collect device details and send this to technical support.",
  "product question": "Answer using the approved product knowledge base.",
};
type Ticket = { id:string; text:string; category:string; predictedCategory:string; model:string; score:number; inferenceMs:number; totalMs:number; reviewed:boolean; policy:string; priority:"Normal"|"High"; timestamp:string; workUnit:Record<string,string|number> };

export default function TicketDesk() {
  const [text,setText]=useState(""); const [sensitivity,setSensitivity]=useState("low"); const [risk,setRisk]=useState("low");
  const [enterprise,setEnterprise]=useState(false); const [busy,setBusy]=useState(false); const [status,setStatus]=useState(""); const [error,setError]=useState(""); const [tickets,setTickets]=useState<Ticket[]>([]);
  const worker=useRef<Worker|null>(null); const pending=useRef<{text:string;policy:string;priority:Ticket["priority"];workUnit:Ticket["workUnit"]}|null>(null); const requestId=useRef(0); const timeout=useRef<ReturnType<typeof setTimeout>|null>(null);
  const metrics=useMemo(()=>({unreviewed:tickets.filter(t=>!t.reviewed).length,average:tickets.length?Math.round(tickets.reduce((sum,t)=>sum+t.inferenceMs,0)/tickets.length):0}),[tickets]);
  useEffect(()=>()=>{worker.current?.terminate();if(timeout.current)clearTimeout(timeout.current)},[]);
  function stop(){requestId.current+=1;worker.current?.terminate();worker.current=null;pending.current=null;if(timeout.current)clearTimeout(timeout.current);setBusy(false);setStatus("Cancelled. Nothing was added to the queue.")}
  async function run(){
    if(busy||!text.trim())return; const currentRequest=++requestId.current; setBusy(true);setError("");setStatus("Preparing your private AI model…"); const input=text.trim();
    const workUnit={workload_id:crypto.randomUUID(),task_type:"classification",complexity:.3,sensitivity,business_value:1,failure_cost:risk==="high"?10:1,escalation_cost:0};
    try{let policy="Kept on this device";
      if(enterprise){setStatus("Checking your company’s AI policy…");const response=await fetch("/enterprise-api/route",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task_type:workUnit.task_type,sensitivity,risk_level:risk}),signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error("Your company policy service is offline. Start it, or turn off company policy to continue privately on this device.");const data=await response.json();if(currentRequest!==requestId.current)return;if(!["direct_small","direct_frontier","verified_cascade"].includes(data.recommended_strategy))throw new Error("The company policy service returned an unknown decision.");policy=`Company policy: ${data.recommended_strategy.replaceAll("_"," ")}`;if(data.recommended_strategy!=="direct_small"){setStatus("Company policy requires a stronger AI service and human review. That service is not connected yet, so no customer text was processed.");setBusy(false);return}}
      pending.current={text:input,policy,priority:risk==="high"?"High":"Normal",workUnit};worker.current??=new Worker(new URL("./model.worker.ts",import.meta.url),{type:"module"});
      worker.current.onmessage=(event)=>{const message=event.data;if(message.type==="progress"){setStatus(message.message);return}if(timeout.current)clearTimeout(timeout.current);setBusy(false);if(message.type==="error"){setError(message.message);return}const current=pending.current;if(!current)return;const {labels,scores}=message.result;setTickets(previous=>[{...current,id:crypto.randomUUID(),category:labels[0],predictedCategory:labels[0],model:"MobileBERT zero-shot classifier",score:scores[0],inferenceMs:message.inferenceMs,totalMs:message.totalMs,reviewed:false,timestamp:new Date().toISOString()},...previous]);pending.current=null;setText("");setStatus("Analysis complete. Check the suggestion before using it.")};
      worker.current.onerror=()=>{stop();setError("The private AI model stopped unexpectedly. Please try again.")};timeout.current=setTimeout(()=>{stop();setError("The model took too long to load. Check your connection and try again.")},180000);worker.current.postMessage({text:input});
    }catch(caught){if(currentRequest!==requestId.current)return;setBusy(false);setError(caught instanceof Error?caught.message:"Unable to analyze this request.")}
  }
  function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(tickets,null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download="inferencemesh-support-queue.json";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  return <section className="ticket-desk">
    <div className="desk-hero"><div><p className="eyebrow">AI SUPPORT ASSISTANT</p><h2>Turn a customer message into a clear next step.</h2><p className="desk-intro">InferenceMesh sorts the request privately, flags its priority, and keeps a person in control of the final decision.</p></div><span className="privacy-badge"><span/>Customer text stays here</span></div>
    <ol className="workflow-steps" aria-label="How it works"><li><span>1</span><div><strong>Add a request</strong><small>Paste a customer message</small></div></li><li><span>2</span><div><strong>AI suggests</strong><small>Category, priority, and action</small></div></li><li><span>3</span><div><strong>You decide</strong><small>Approve or correct the result</small></div></li></ol>
    <div className="desk-metrics"><div><span>Requests analyzed</span><strong>{tickets.length}</strong></div><div><span>Waiting for review</span><strong>{metrics.unreviewed}</strong></div><div><span>Average AI time</span><strong>{metrics.average?`${metrics.average} ms`:"—"}</strong></div></div>
    <div className="desk-layout"><article className="desk-panel compose-panel"><div className="panel-title"><span className="panel-number">1</span><div><h3>What did the customer say?</h3><p>Choose an example or paste a real support request.</p></div></div>
      <div className="example-chips">{examples.map(([label,value])=><button key={label} onClick={()=>setText(value)} disabled={busy}>{label}</button>)}</div>
      <label htmlFor="ticket-text">Customer message</label><textarea id="ticket-text" value={text} onChange={e=>setText(e.target.value)} maxLength={2000} rows={7} placeholder="Paste the customer’s message here…" disabled={busy}/><div className="character-count">{text.length}/2,000</div>
      <div className="decision-options"><label>Does it contain sensitive information?<select value={sensitivity} onChange={e=>setSensitivity(e.target.value)} disabled={busy}><option value="low">No sensitive information</option><option value="high">Yes — keep on this device</option></select></label><label>What if the AI is wrong?<select value={risk} onChange={e=>setRisk(e.target.value)} disabled={busy}><option value="low">Low impact</option><option value="high">High impact — require extra review</option></select></label></div>
      <label className="policy-toggle"><input type="checkbox" checked={enterprise} onChange={e=>setEnterprise(e.target.checked)} disabled={busy}/><span><strong>Apply company AI policy</strong><small>Ask your enterprise router which approved AI path should handle this request. The message itself is not sent.</small></span></label>
      <button className="analyze-button" onClick={()=>void run()} disabled={busy||!text.trim()}>{busy?"Analyzing request…":"Analyze request"}<span>→</span></button>{busy&&<button className="quiet-button" onClick={stop}>Cancel</button>}{status&&<p className="desk-status" role="status">{status}</p>}{error&&<p role="alert" className="room-error">{error}</p>}
    </article><article className="desk-panel queue-panel"><div className="queue-heading"><div className="panel-title"><span className="panel-number">2</span><div><h3>Review the suggestion</h3><p>You make the final call.</p></div></div><button className="export-button" disabled={!tickets.length} onClick={download}>Export</button></div>
      {!tickets.length?<div className="desk-empty"><div className="empty-icon">✓</div><h3>Your review queue is clear</h3><p>Analyze a message and the recommended category, priority, and next step will appear here.</p></div>:<div className="ticket-list">{tickets.map(ticket=><article className="ticket-row" key={ticket.id}><div className="ticket-topline"><span className={`priority priority-${ticket.priority.toLowerCase()}`}>{ticket.priority} priority</span><span className={ticket.reviewed?"reviewed":"needs-review"}>{ticket.reviewed?"Approved":"Needs your review"}</span></div><blockquote>{ticket.text}</blockquote><div className="recommendation"><span>Suggested next step</span><strong>{actions[ticket.category]}</strong></div><label>Best category<select value={ticket.category} onChange={e=>setTickets(items=>items.map(item=>item.id===ticket.id?{...item,category:e.target.value,reviewed:false}:item))}>{categories.map(category=><option key={category}>{category}</option>)}</select></label><button className="approve-button" onClick={()=>setTickets(items=>items.map(item=>item.id===ticket.id?{...item,reviewed:true}:item))} disabled={ticket.reviewed}>{ticket.reviewed?"Approved":"Approve and add to queue"}</button><details><summary>Why did InferenceMesh suggest this?</summary><p>The browser model matched this most closely to <strong>{ticket.predictedCategory}</strong> with a {(ticket.score*100).toFixed(1)}% comparison score.</p><dl><div><dt>Where it ran</dt><dd>{ticket.policy}</dd></div><div><dt>Model</dt><dd>{ticket.model}</dd></div><div><dt>AI time</dt><dd>{Math.round(ticket.inferenceMs)} ms</dd></div><div><dt>Total time</dt><dd>{(ticket.totalMs/1000).toFixed(2)} s</dd></div></dl><small>A model score compares the available categories; it is not a guarantee of correctness.</small></details></article>)}</div>}
      <p className="session-note">This queue lasts for this browser session. Export it before refreshing if you want to keep the results.</p></article></div>
  </section>
}
